// web/src/apps/bleeter/bleeter-app.svelte
<script lang="ts">
  import { fly } from "svelte/transition";
  import { ACTIVE_PAGE, SELECTED_USER, SELECTED_BLEET } from "./stores/bleeter";
  import { Plus, BellDot, Home, Search, User } from "lucide-svelte";
  import HomePage from "./pages/home/home-page.svelte";
  import SearchPage from "./pages/search/search-page.svelte";
  import NotificationsPage from "./pages/notifications/notifications-page.svelte";
  import ProfilePage from "./pages/profile/profile-page.svelte";
  import BottomNav from "@/components/shared/bottom-nav.svelte";
  import BleetPage from "./pages/bleet/bleet-page.svelte";

  const pageComponents: { [key: string]: any } = {
    home: HomePage,
    search: SearchPage,
    notifications: NotificationsPage,
    profile: ProfilePage,
  };

  const buttons = [
    { icon: Home, page: "home" },
    { icon: Search, page: "search" },
    { icon: BellDot, page: "notifications" },
    { icon: User, page: "profile" },
  ];

  function setActivePage(page: string) {
    ACTIVE_PAGE.set(page);
    SELECTED_USER.set(null);
    SELECTED_BLEET.set(null);
  }
</script>

<div class="relative flex flex-col w-full h-full bg-background">
  <svelte:component this={pageComponents[$ACTIVE_PAGE]} />

  {#if $SELECTED_USER}
    <div
      class="absolute inset-0 flex flex-col bg-background"
      transition:fly={{ x: 500, duration: 300 }}
    >
      <ProfilePage isOverlay={true} />
    </div>
  {/if}

  {#if $SELECTED_BLEET}
    <div
      class="absolute inset-0 flex flex-col bg-background"
      transition:fly={{ x: 500, duration: 300 }}
    >
      <BleetPage />
    </div>
  {/if}

  <button
    class="absolute bottom-0 right-0 flex items-center justify-center m-4 rounded-full shadow-md size-16 mb-28 bg-secondary hover:opacity-80 group"
  >
    <Plus class="text-gray-400 group-hover:text-foreground" />
  </button>

  <BottomNav {buttons} {setActivePage} activePage={$ACTIVE_PAGE} />
</div>

// src/apps/bleeter/bleeter-app.tsx
import { useState } from 'react';
import { BleeterNav } from "./components/nav";
import { BleeterHomePage } from "./pages/home/home-page";
import { BleeterSearchPage } from "./pages/search/search-page";
import { BleeterNotificationsPage } from './pages/notifications/notifications-page';
import { BleeterProfilePage } from './pages/profile/profile-page';
import { Plus } from 'lucide-react';

export function BleeterApp() {
  const [activePage, setActivePage] = useState('home');

  const renderPage = () => {
    switch (activePage) {
      case 'home':
        return <BleeterHomePage />;
      case 'search':
        return <BleeterSearchPage />;
      case 'notifications':
        return <BleeterNotificationsPage />;
      case 'profile':
        return <BleeterProfilePage isOwnProfile={true} hasBackButton={false} />;
      default:
        return <BleeterHomePage />;
    }
  };

  return (
    <div className="flex flex-col w-full h-full bg-background">
      {renderPage()}
      <button className="absolute bottom-0 right-0 flex items-center justify-center m-4 rounded-full shadow-md w-14 h-14 mb-28 bg-secondary hover:bg-muted group">
        <Plus className="text-gray-400 group-hover:text-foreground" />
      </button>
      <BleeterNav activePage={activePage} setActivePage={setActivePage} />
    </div>
  );
}
