// src/apps/phone/phone-app.tsx
import { useState } from "react";
import { PhoneNav } from "./components/nav";
import { RecentCallsPage } from "./pages/recent-calls";
import { ContactsPage } from "./pages/contacts";
import { FavoritesPage } from "./pages/favorites";
import { KeyPadPage } from "./pages/keypad";

export function PhoneApp() {
  const [activePage, setActivePage] = useState('recentCalls');

  const renderPage = () => {
    switch (activePage) {
      case 'favorites':
        return <FavoritesPage />;
      case 'recentCalls':
        return <RecentCallsPage />;
      case 'contacts':
        return <ContactsPage />;
      case 'keypad':
        return <KeyPadPage />;
      default:
        return <RecentCallsPage />;
    }
  };

  return (
    <div className="flex flex-col w-full h-full bg-background">
      {renderPage()}
      <PhoneNav activePage={activePage} setActivePage={setActivePage} />
    </div>
  );
}

// web/src/apps/phone/phone-app.svelte
<script lang="ts">
  import { Star, Clock, Contact, Grip } from "lucide-svelte";
  import { ACTIVE_PAGE } from "./stores/phone";
  import ContactsPage from "./pages/contacts/contacts-page.svelte";
  import RecentCallsPage from "./pages/recent-calls/recent-calls-page.svelte";
  import FavoritesPage from "./pages/favorites/favorites-page.svelte";
  import KeypadPage from "./pages/keypad/keypad-page.svelte"
  import BottomNav from "@/components/bottom-nav.svelte";

  const pageComponents: { [key: string]: any } = {
    contacts: ContactsPage,
    recentCalls: RecentCallsPage,
    favorites: FavoritesPage,
    keypad: KeypadPage,
  };
  
  const buttons = [
    { icon: Star, page: "favorites" },
    { icon: Clock, page: "recentCalls" },
    { icon: Contact, page: "contacts" },
    { icon: Grip, page: "keypad" }
  ];
</script>

<div class="relative flex flex-col w-full h-full bg-background">
  <svelte:component this={pageComponents[$ACTIVE_PAGE]} />
  <BottomNav
    {buttons}
    setActivePage={(page) => ACTIVE_PAGE.set(page)}
    activePage={$ACTIVE_PAGE}
  />
</div>
