// web/src/layout/components/indicator.svelte
<script>
  let { onclick } = $props();
</script>

<button
  class="absolute bottom-0 z-50 flex items-center justify-center w-full h-8 transition-all group"
  aria-label="indicator"
  {onclick}
>
  <div
    class="bg-foreground/80 w-52 rounded-full min-h-1.5 group-hover:bg-foreground/60"
  ></div>
</button>

// src/components/os/indicator.tsx
interface IndicatorProps {
  onIndicatorClick?: () => void;
}

export function Indicator({ onIndicatorClick }: IndicatorProps) {
  return (
    <button
      className="absolute bottom-0 z-50 flex items-center justify-center w-full h-8 transition-all group"
      onClick={onIndicatorClick}
      aria-label="indicator"
    >
      <div className=" bg-foreground/80 w-60 rounded-full min-h-1.5 group-hover:bg-foreground/60" />
    </button>
  );
}
