// src/components/os/lockscreen.tsx
import { motion } from "framer-motion";
import { Indicator } from "./indicator";
import Background from "@/assets/backgrounds/ifruit.webp";

interface LockscreenProps {
  showIndicator?: boolean | null;
  onIndicatorClick?: () => void;
  isAnimating?: boolean;
}

export function Lockscreen({
  showIndicator,
  onIndicatorClick,
  isAnimating,
}: LockscreenProps): JSX.Element {
  return (
    <motion.div
      className="flex items-center justify-center w-full h-full bg-cover lockscreen"
      initial={{ y: 0 }}
      animate={{ y: isAnimating ? '-100%' : 0 }}
      transition={{ duration: 0.3, ease: "easeInOut" }}
      style={{ backgroundImage: `url(${Background})` }}
    >
      <p className="text-lg font-medium mb-36">21:10</p>
      {showIndicator && <Indicator onIndicatorClick={onIndicatorClick} />}
    </motion.div>
  );
}

// web/src/phone/components/lockscreen.svelte
<script>
  import Background from "@/lib/assets/backgrounds/background.webp";
  import { core } from "@/lib/states/core.svelte";
  import { quintOut } from "svelte/easing";
  import { slide } from "svelte/transition";
  import Indicator from "./indicator.svelte";

  function unlock() {
    core.isLocked = false;
  }
</script>

<div
  class="absolute w-full h-full flex items-center justify-center bg-cover z-10"
  style="background-image: url({Background});"
  out:slide={{ duration: 400, easing: quintOut, axis: "y" }}
>
  <Indicator onclick={unlock} />
</div>
