// web/src/apps/settings/pages/cloud/cloud-page.svelte
<script>
  import { onMount } from "svelte";
  import { ChevronLeft, Cloud, LogOut } from "lucide-svelte";
  import { goBack, navigateTo } from "../../stores/settings";

  let loggedIn = true;

  onMount(() => {
    if (!loggedIn) {
      navigateTo("cloudLogin");
    }
  });

  function handleLogout() {
    // Implement logout logic here
    loggedIn = false;
    navigateTo("cloudLogin");
  }
</script>

<!-- Todo: maybe new design? -->

<header class="flex items-center w-full gap-4 px-6 pb-4 mt-16 border-b">
  <button onclick={goBack} class="text-gray-400 hover:text-foreground">
    <ChevronLeft className="w-6 h-6" />
  </button>
  <p class="font-medium">Cloud</p>
</header>

<div class="flex items-center justify-between w-full h-16 px-6 border-b hover:bg-secondary/70 dark:hover:bg-secondary/20">
  <div class="flex items-center space-x-4 w-full">
    <Cloud />
    <p class="text-base">Cloud synced</p>
  </div>
</div>

<button onclick={handleLogout} class="flex space-x-4 items-center w-full h-16 px-6 border-b hover:bg-secondary/70 dark:hover:bg-secondary/20 hover:text-destructive">
  <LogOut />
  <p class="text-base">Logout</p>
</button>

// src/apps/settings/pages/cloud-page.tsx
import { ScrollArea } from "@/components/ui/scroll-area";
import { ChevronLeft, ChevronRight, Settings2 } from "lucide-react";

interface SettingsCloudPageProps {
  onBack: () => void;
}

export default function SettingsCloudPage({ onBack }: SettingsCloudPageProps) {
  return(
    <>
      <header className="flex items-center w-full gap-4 px-6 pb-4 mt-[4.5rem] border-b">
        <button onClick={onBack} className="text-gray-400 hover:text-foreground">
          <ChevronLeft className="w-6 h-6 text-gray-400 hover:text-foreground" />
        </button>
        <p className="font-medium">General</p>
      </header>
      <ScrollArea className="flex flex-col flex-grow w-full overflow-y-auto">
        <button className="flex items-center justify-between w-full h-20 px-6 border-b hover:bg-secondary/70 dark:hover:bg-secondary/20">
          <div className="flex items-center space-x-4">
            <Settings2 />
            <div className="text-left">
              <p className="text-base">General</p>
              <p className="text-sm text-gray-400">All the basic stuff that actually matters</p>
            </div>
          </div>
          <ChevronRight className="w-4 h-4 text-gray-400" />
        </button>
      </ScrollArea>
    </>
  )
}
