// web/src/lib/components/ui/switch/switch.svelte
<script lang="ts">
  interface Props {
    checked?: boolean;
    onChange?: (value: boolean) => void;
    disabled?: boolean;
    class?: string | undefined;
  }

  let {
    checked = $bindable(false),
    onChange = (value: boolean) => {},
    disabled = false,
    class: className = undefined,
    ...rest
  }: Props = $props();

  function toggle() {
    if (!disabled) {
      checked = !checked;
      onChange(checked);
    }
  }
</script>

<button
  type="button"
  role="switch"
  aria-checked={checked}
  aria-label={checked ? "On" : "Off"}
  {disabled}
  class="peer inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors disabled:cursor-not-allowed disabled:opacity-50 focus-visible:border-ring/20 {checked
    ? 'bg-primary'
    : 'bg-input'} {className}"
  onclick={(e) => {
    e.stopPropagation();
    toggle();
  }}
  {...rest}
>
  <span
    class="bg-background pointer-events-none block h-4 w-4 rounded-full shadow-lg ring-0 transition-transform {checked
      ? 'translate-x-4'
      : 'translate-x-0'}"
  ></span>
</button>

// src/components/ui/switch.tsx
import * as React from "react"
import * as SwitchPrimitives from "@radix-ui/react-switch"

import { cn } from "@/utils/misc"

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input",
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0"
      )}
    />
  </SwitchPrimitives.Root>
))
Switch.displayName = SwitchPrimitives.Root.displayName

export { Switch }
