// src/components/phone-wrapper.tsx
import { ReactNode } from "react";
import Background from "@/assets/backgrounds/ifruit.webp"
import { Notch } from "./os/notch";

interface PhoneWrapperProps {
  children: ReactNode;
}

export default function PhoneWrapper({ children }: PhoneWrapperProps) {
  return(
    <>
      <div
        className="absolute flex w-[30rem] h-[63rem]"
        style={{
          transform: `scale(0.8)`,
        }}
      >
        <div className="absolute w-full">
          <button className="absolute z-50 w-1 h-32 bg-[#797683] shadow-inner rounded-full left-[30.3rem] top-44" aria-label="close"></button>
          <div className="h-32 w-1.5 top-32 absolute flex flex-col z-0">
            <button className="absolute w-full h-12 bg-[#797683] shadow-inner rounded-full right-2.5" aria-label="mute"></button>
            <button className="absolute w-full h-24 bg-[#797683] shadow-inner rounded-full right-2.5 top-24" aria-label="volume-up"></button>
            <button className="absolute w-full h-24 bg-[#797683] shadow-inner rounded-full right-2.5 top-56" aria-label="volume-down"></button>
          </div>
        </div>
        <div className="w-full h-full bg-black rounded-[3.5rem] shadow-frame p-3 flex z-10">
          <Notch />
          <div
            className="w-full h-full rounded-[3rem] bg-cover bg-black overflow-hidden"
            // style={{backgroundImage: `url(${Background})`}} 
          >
            {children}
          </div>
        </div>
      </div>
    </>
  )
}

// web/src/layout/components/phone-wrapper.svelte
<script lang="ts">
  import Background from "@/assets/backgrounds/background.webp";
  import { Signal, WifiHigh } from "lucide-svelte";
  import { IS_LOCKED } from "@/stores/phone";
  import Notch from "./notch.svelte";
  import Notifications from "./notifications.svelte";

  function lock() {
    IS_LOCKED.set(true);
  }
</script>

<div class="absolute flex w-[30rem] h-[63rem]" style="scale: 0.8">
  <button
    class="absolute w-1.5 h-32 bg-gray-500 shadow-inner shadow-[#241D24] rounded-full top-48 right-[-10px]"
    aria-label="Lock"
    on:click={lock}
  />

  <div class="h-32 w-1.5 absolute flex flex-col left-[-10px] top-36">
    <button
      class="w-full min-h-12 bg-gray-500 shadow-inner shadow-[#241D24] rounded-full mb-8"
      aria-label="Mute"
    />
    <button
      class="w-full min-h-24 bg-gray-500 shadow-inner shadow-[#241D24] rounded-full mb-4"
      aria-label="Volume up"
    />
    <button
      class="w-full min-h-24 bg-gray-500 shadow-inner shadow-[#241D24] rounded-full"
      aria-label="Volume down"
    />
  </div>

  <!-- Phone content -->
  <div class="w-full h-full bg-black rounded-[3.4rem] shadow-frame flex z-10 p-2 overflow-hidden">
    <Notch />
    <div class="w-full h-full rounded-[3rem] bg-cover bg-black overflow-hidden relative "  style="background-image: url({Background});">
      <header class="absolute z-50 flex items-center justify-between w-full px-8 pt-4">
        <p class="font-medium">13:03</p>
        <button class="flex gap-2" aria-label="Control center">
          <WifiHigh class="mb-2 w-7 h-7" />
          <Signal class="w-6 h-6 mt-[0.40rem]" />
        </button>
      </header>
      <Notifications />
      <slot />
    </div>
  </div>
</div>
